# Generated by Django 2.2.7 on 2019-11-21 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qrcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('url_interno', models.CharField(blank=True, max_length=200, null=True)),
                ('url_redirecionado', models.CharField(blank=True, max_length=200, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('caminho', models.FilePathField(blank=True, default='', null=True, recursive=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('data_inativo', models.DateTimeField(blank=True, null=True)),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qrcode',
            },
        ),
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(blank=True, max_length=40, null=True)),
                ('sistema', models.CharField(blank=True, max_length=40, null=True)),
                ('navegador', models.CharField(blank=True, max_length=200, null=True)),
                ('local', models.CharField(blank=True, max_length=40, null=True)),
                ('fk_qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrcodegen.Qrcode')),
            ],
            options={
                'db_table': 'acesso',
            },
        ),
    ]
