# Generated by Django 2.2.7 on 2019-11-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodegen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='acessos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
