# Generated by Django 2.2.7 on 2019-11-23 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodegen', '0002_qrcode_acessos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='acessos',
        ),
    ]
