# Generated by Django 5.2.7 on 2025-10-31 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qrcodegen", "0003_remove_qrcode_acessos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcode",
            name="fk_user",
        ),
        migrations.DeleteModel(
            name="Acesso",
        ),
        migrations.DeleteModel(
            name="Qrcode",
        ),
    ]
